# -*- coding: utf-8 -*-
require 'fileutils'
require 'tmpdir'

FORTRAN_COMPILER = "gfortran-mp-4.7"
FORTRAN_OPTIONS = %w[
  -Wall
  -ffree-line-length-none
  -cpp
  -C
  -fmax-identifier-length=63
  -fbacktrace -pipe
].join(' ')

CPP = "cpp-mp-4.7"
CPP_OPTIONS = %w[
  -C
].join(' ')

task default: :compile
task compile: %w[displacement_after.exe]

task :test do
  FileUtils.cd('test'){
    sh "../displacement_after.exe"
  }
end

file "displacement_after.exe" => %w[lib_character.o lib_io.o displacement_after.o] do |t|
  sh "#{FORTRAN_COMPILER} #{FORTRAN_OPTIONS} -o #{t.name} #{t.prerequisites.join(' ')}"
end

rule ".o" => ".f90" do |t|
  Dir.mktmpdir{|tmpdir|
    tempfile = File.join(tmpdir, t.source)
    FileUtils.mkdir_p File.dirname(tempfile)
    sh "#{CPP} #{CPP_OPTIONS} #{t.source} > #{tempfile}" # ifort対応で、個別にcppしている。
    sh "#{FORTRAN_COMPILER} #{FORTRAN_OPTIONS} -c #{tempfile}"
  }
end
